name: Create and Update Translation Branches and PRs

# This will run when there is a push to any English language branch
# With the format listed below.
on:
  push:
    branches:
      - 'handbook_v*_en'

jobs:
  create_and_update_translation_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'ntluong95'
          git config --global user.email 'ph.ntluong95@gmail.com'

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Fetch all branches
        run: git fetch --all

      - name: Create and update language branches and PRs
        run: |
          LANGS=("fr" "es" "vn" "jp" "tr" "pt" "ru")  
          EN_BRANCH="${{ github.ref }}"
          VERSION_SUFFIX="${EN_BRANCH#refs/heads/handbook_}"

          for lang in "${LANGS[@]}"; do
            TRANSLATION_BRANCH="handbook_${VERSION_SUFFIX/_en/_$lang}"
            git fetch --prune

            # Ensure we have all history
            git fetch --all
            
            # Check if the translation branch exists
            if git ls-remote --exit-code --heads origin "${TRANSLATION_BRANCH}"; then
              echo "Branch ${TRANSLATION_BRANCH} exists. Checking out and rebasing with ${EN_BRANCH}"
              git checkout "${TRANSLATION_BRANCH}"
              git pull -s recursive -X theirs --no-rebase --no-edit origin "${EN_BRANCH#refs/heads/}" --allow-unrelated-histories
              
            else
              echo "Branch ${TRANSLATION_BRANCH} does not exist. Creating new branch from ${EN_BRANCH}."
              git checkout -b "${TRANSLATION_BRANCH}"
              git pull origin "${EN_BRANCH#refs/heads/}"
            fi
            
            # Force push the changes to the remote repository
            git push origin "${TRANSLATION_BRANCH}" --force

            # Get the list of changed .qmd files compared with main branch
            changed_files=$(git diff --name-only origin/main "${TRANSLATION_BRANCH}" | grep '\.qmd$')

            if [ -z "$changed_files" ]; then
              echo "No .qmd file changes to include in PR for ${TRANSLATION_BRANCH}"
              continue
            fi

            echo "Changed files: $changed_files"
            
            # Get the date of the latest commit on the translation branch
            latest_translation_commit_date=$(git log -1 --format=%ci "${TRANSLATION_BRANCH}")
            
            # Get the list of commits on the English branch since the latest translation commit
            latest_commits=$(git log ${EN_BRANCH} --since="${latest_translation_commit_date}" --format="%H")

            if [ -z "$latest_commits" ]; then
              echo "No new commits to include in PR for ${TRANSLATION_BRANCH}"
              continue
            fi

            # Check if a PR already exists for this branch
            PR_EXISTS=$(gh pr list --head "${TRANSLATION_BRANCH}" --state open --json number --jq length)
            if [ "$PR_EXISTS" -eq 0 ]; then
              echo "Creating new PR for ${TRANSLATION_BRANCH}"
              PR_URL=$(gh pr create --base deploy-preview --head "$TRANSLATION_BRANCH" --title "Handbook ${VERSION_SUFFIX/_en/} $lang" --body "Automated pull request for $lang handbook version ${VERSION_SUFFIX/_en/}")
              PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
            else
              # Get the PR number for the translation branch
              echo "PR already exists for ${TRANSLATION_BRANCH}"
              PR_NUMBER=$(gh pr list --head "${TRANSLATION_BRANCH}" --state open --json number --jq ".[0].number")
            fi

            echo "Pull Request Number: $PR_NUMBER"

            # Set the translator username based on language
            case "$lang" in
              "vn") TRANSLATOR_USERNAME="ntluong95" ;;
              "fr") TRANSLATOR_USERNAME="fr-translator" ;;
              "es") TRANSLATOR_USERNAME="es-translator" ;;
              "jp") TRANSLATOR_USERNAME="jp-translator" ;;
              "tr") TRANSLATOR_USERNAME="tr-translator" ;;
              "pt") TRANSLATOR_USERNAME="pt-translator" ;;
              "ru") TRANSLATOR_USERNAME="ru-translator" ;;
              *) TRANSLATOR_USERNAME="translator" ;;
            esac

            # Initialize new PR body
            new_pr_body="# Automated pull request for $lang handbook version ${VERSION_SUFFIX/_en/}"
            
            # Add new commits as checkboxes to the PR description
            IFS=$'\n' # Change the Internal Field Separator to newline for correct iteration over lines
            checkboxes=""
            for file in $changed_files; do
              # Get the list of commits where the file changed
              file_commits=""
              for commit in $latest_commits; do
                if git diff-tree --no-commit-id --name-only -r $commit | grep -q "$file"; then
                  # Build the commit link
                  commit_link="[\`${commit:0:7}\`](https://github.com/${{ github.repository }}/commit/$commit)"
                  file_commits="$file_commits $commit_link"
                fi
              done

              if [ -n "$file_commits" ]; then
                # Build the checkbox line
                checkbox="- [ ] Chapter [\`$file\`](https://github.com/${{ github.repository }}/blob/${EN_BRANCH#refs/heads/}/$file) has new changes in the following commit(s):$file_commits @$TRANSLATOR_USERNAME, please review changes and check the box when you finish"
                checkboxes="$checkboxes"$'\n'"$checkbox"
              fi
            done

            if [ -n "$checkboxes" ]; then
              # Append the checkboxes to the new PR body
              new_pr_body="$new_pr_body"$'\n'"$checkboxes"
            fi

            # Update the PR description
            gh api repos/${{ github.repository }}/issues/$PR_NUMBER --method PATCH --field body="$new_pr_body"
            
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
